// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF-5gN1-8yzfSOw34pwvh54_xdaqlfWL4',
    appId: '1:848693712083:web:aa1f37b44fb96b5327f026',
    messagingSenderId: '848693712083',
    projectId: 'bric-d-up',
    authDomain: 'bric-d-up.firebaseapp.com',
    storageBucket: 'bric-d-up.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqAZIwyQBUzoldGDN5h5zme-LilZhRCfg',
    appId: '1:848693712083:android:dc68424edf1837be27f026',
    messagingSenderId: '848693712083',
    projectId: 'bric-d-up',
    storageBucket: 'bric-d-up.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9zXYceyy-nExWZbC-RX8Sh6jthdnyr2k',
    appId: '1:848693712083:ios:8320bfae66081b6627f026',
    messagingSenderId: '848693712083',
    projectId: 'bric-d-up',
    storageBucket: 'bric-d-up.firebasestorage.app',
    iosBundleId: 'com.example.bricdUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9zXYceyy-nExWZbC-RX8Sh6jthdnyr2k',
    appId: '1:848693712083:ios:8320bfae66081b6627f026',
    messagingSenderId: '848693712083',
    projectId: 'bric-d-up',
    storageBucket: 'bric-d-up.firebasestorage.app',
    iosBundleId: 'com.example.bricdUp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAF-5gN1-8yzfSOw34pwvh54_xdaqlfWL4',
    appId: '1:848693712083:web:327b61d1ed28ea7027f026',
    messagingSenderId: '848693712083',
    projectId: 'bric-d-up',
    authDomain: 'bric-d-up.firebaseapp.com',
    storageBucket: 'bric-d-up.firebasestorage.app',
  );
}
